# Generated by Django 4.2.4 on 2025-08-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTracking',
        ),
    ]
