# Generated by Django 4.2.4 on 2025-08-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truckdocument'),
        ('orders', '0003_delete_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trucks.truck'),
        ),
    ]
