# Generated by Django 4.2.4 on 2025-07-05 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_base_price', models.DecimalField(decimal_places=2, default=0, help_text='Combined base price for all trucks', max_digits=10)),
                ('total_fuel_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_toll_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_loading_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_unloading_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_additional_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('validity_hours', models.PositiveIntegerField(default=24, help_text='Quote validity in hours')),
                ('customer_suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_response_to_suggestion', models.TextField(blank=True, help_text="Vendor's response to customer's suggested price")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('negotiating', 'Under Negotiation'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_address', models.TextField()),
                ('pickup_date', models.DateTimeField()),
                ('delivery_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_address', models.TextField()),
                ('expected_delivery_date', models.DateTimeField()),
                ('cargo_description', models.TextField(blank=True)),
                ('estimated_total_weight', models.DecimalField(decimal_places=2, default=0, help_text='Total weight in tons', max_digits=8)),
                ('special_instructions', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('suggested_total_price', models.DecimalField(blank=True, decimal_places=2, help_text="Customer's suggested total price", max_digits=10, null=True)),
                ('suggested_price_notes', models.TextField(blank=True, help_text="Customer's notes about suggested pricing")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_quotation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], max_length=10)),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('proposed_base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_fuel_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_toll_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_loading_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_unloading_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_additional_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='quotations.quotation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotations.quotationrequest'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuotationRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of trucks of this type needed')),
                ('item_weight', models.DecimalField(decimal_places=2, help_text='Weight for this truck type in tons', max_digits=8)),
                ('item_special_instructions', models.TextField(blank=True, help_text='Special instructions for this truck type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotationrequest')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
            options={
                'unique_together': {('quotation_request', 'truck')},
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_base_price', models.DecimalField(decimal_places=2, help_text='Base price per truck', max_digits=10)),
                ('unit_fuel_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_toll_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_loading_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_unloading_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_additional_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
            options={
                'unique_together': {('quotation', 'truck')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('quotation_request', 'vendor')},
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_weight', models.DecimalField(decimal_places=2, help_text='Weight for this truck type in tons', max_digits=8)),
                ('item_special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.cart')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
            options={
                'unique_together': {('cart', 'truck')},
            },
        ),
    ]
