# Generated by Django 4.2.4 on 2025-08-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_customerenquiry_route_pricerange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerenquiry',
            name='delivery_pincode',
            field=models.CharField(blank=True, help_text='Delivery pincode', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='pickup_pincode',
            field=models.CharField(blank=True, help_text='Pickup pincode', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_pincode',
            field=models.CharField(blank=True, help_text='Primary pincode for destination city', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_pincode',
            field=models.CharField(blank=True, help_text='Primary pincode for origin city', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop_pincode',
            field=models.CharField(blank=True, help_text='Primary pincode for stop city', max_length=10, null=True),
        ),
    ]
