# Generated by Django 4.2.4 on 2025-08-03 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0003_customerenquiry_delivery_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_pincode', models.CharField(max_length=10)),
                ('destination_pincode', models.CharField(max_length=10)),
                ('pickup_date', models.DateTimeField()),
                ('drop_date', models.DateTimeField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in tonnes', max_digits=8)),
                ('weight_unit', models.CharField(default='tonnes', max_length=10)),
                ('urgency_level', models.CharField(default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active - Collecting Quotes'), ('confirmed', 'Order Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='enquiry',
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='supporting_routes',
        ),
        migrations.AlterUniqueTogether(
            name='vendorenquiryrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendorenquiryrequest',
            name='enquiry',
        ),
        migrations.RemoveField(
            model_name='vendorenquiryrequest',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='vendorenquiryrequest',
            name='route',
        ),
        migrations.RemoveField(
            model_name='vendorenquiryrequest',
            name='sent_by_manager',
        ),
        migrations.RemoveField(
            model_name='vendorenquiryrequest',
            name='vendor',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='total_additional_charges',
            new_name='additional_charges',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='total_fuel_charges',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='total_loading_charges',
            new_name='fuel_charges',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='total_toll_charges',
            new_name='loading_charges',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='total_unloading_charges',
            new_name='toll_charges',
        ),
        migrations.RenameField(
            model_name='quotationitem',
            old_name='unit_additional_charges',
            new_name='unit_price',
        ),
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quotation',
            name='frontend_vendor_id',
            field=models.CharField(blank=True, help_text='Frontend vendor ID', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unloading_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Frontend vendor name', max_length=200),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_data',
            field=models.JSONField(blank=True, help_text='Raw item data from frontend', null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='destination_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='origin_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('negotiating', 'Under Negotiation'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('on_demand', 'On Demand'), ('multiple_daily', 'Multiple Daily'), ('alternate_days', 'Alternate Days')], default='weekly', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomerEnquiry',
        ),
        migrations.DeleteModel(
            name='PriceRange',
        ),
        migrations.DeleteModel(
            name='VendorEnquiryRequest',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='confirmed_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='item_notes',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_base_price',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_fuel_charges',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_loading_charges',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_toll_charges',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_unloading_charges',
        ),
        migrations.AddField(
            model_name='quotation',
            name='order_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotations.orderrequest'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='order_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to='quotations.orderrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('order_request', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='quotationrequest',
            unique_together={('order_request', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='orderrequest',
            unique_together={('customer', 'origin_pincode', 'destination_pincode', 'pickup_date', 'drop_date')},
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer_suggested_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quotation_request',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_base_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='vendor_response_to_suggestion',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='estimated_total_weight',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='suggested_price_notes',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='suggested_total_price',
        ),
    ]
