# Generated by Django 4.2.4 on 2025-08-04 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0002_truckdocument'),
        ('quotations', '0004_orderrequest_remove_pricerange_enquiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_pincode', models.CharField(blank=True, help_text='Pickup pincode', max_length=10, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_pincode', models.CharField(blank=True, help_text='Delivery pincode', max_length=10, null=True)),
                ('expected_delivery_date', models.DateTimeField()),
                ('number_of_vehicles', models.PositiveIntegerField(default=1)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cargo_description', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_miscellaneous_route', models.BooleanField(default=False, help_text='Route not covered by regular vendors')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('quotes_generated', 'Quotes Generated'), ('quote_selected', 'Quote Selected'), ('sent_to_vendors', 'Sent to Vendors'), ('vendor_responses', 'Vendor Responses Received'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_vendor_size', models.CharField(choices=[('small', 'Small Vendor'), ('medium', 'Medium Vendor'), ('large', 'Large Vendor'), ('any', 'Any Size')], default='any', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_enquiries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicles_available', models.PositiveIntegerField()),
                ('vendors_count', models.PositiveIntegerField()),
                ('chance_of_getting_deal', models.CharField(choices=[('low', 'Low (10-30%)'), ('medium', 'Medium (40-70%)'), ('high', 'High (80-95%)')], max_length=10)),
                ('route_type', models.CharField(choices=[('direct', 'Direct Route'), ('via_stops', 'Via Multiple Stops'), ('miscellaneous', 'Non-standard Route')], max_length=20)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('includes_fuel', models.BooleanField(default=True)),
                ('includes_tolls', models.BooleanField(default=True)),
                ('includes_loading', models.BooleanField(default=True)),
                ('additional_charges_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='quotations.customerenquiry')),
            ],
            options={
                'ordering': ['min_price'],
            },
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='additional_charges',
            new_name='total_additional_charges',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='base_price',
            new_name='total_fuel_charges',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='fuel_charges',
            new_name='total_loading_charges',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='loading_charges',
            new_name='total_toll_charges',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='toll_charges',
            new_name='total_unloading_charges',
        ),
        migrations.RenameField(
            model_name='quotationitem',
            old_name='unit_price',
            new_name='unit_additional_charges',
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quotationrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotations.quotationrequest'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Combined base price for all trucks', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_response_to_suggestion',
            field=models.TextField(blank=True, help_text="Vendor's response to customer's suggested price"),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trucks.truck'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price per truck', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_fuel_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_loading_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_toll_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_unloading_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='estimated_total_weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total weight in tons', max_digits=8),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='expected_delivery_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='pickup_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='suggested_price_notes',
            field=models.TextField(blank=True, help_text="Customer's notes about suggested pricing"),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='suggested_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's suggested total price", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('negotiating', 'Under Negotiation'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='delivery_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='pickup_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('on_demand', 'On Demand')], default='weekly', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('quotation_request', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together={('quotation', 'truck')},
        ),
        migrations.CreateModel(
            name='VendorEnquiryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manager_notes', models.TextField(blank=True)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent to Vendor'), ('viewed', 'Viewed by Vendor'), ('quoted', 'Vendor Quoted'), ('accepted', 'Vendor Accepted'), ('rejected', 'Vendor Rejected'), ('expired', 'Expired')], default='sent', max_length=20)),
                ('vendor_response_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_response_notes', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requests', to='quotations.customerenquiry')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.pricerange')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.route')),
                ('sent_by_manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_vendor_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_enquiry_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('enquiry', 'vendor', 'price_range')},
            },
        ),
        migrations.AddField(
            model_name='pricerange',
            name='supporting_routes',
            field=models.ManyToManyField(blank=True, to='quotations.route'),
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='matched_routes',
            field=models.ManyToManyField(blank=True, related_name='enquiries', to='quotations.route'),
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.trucktype'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='frontend_vendor_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='order_request',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='unloading_charges',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='vendor_name',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='item_data',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='order_request',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='origin_location',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='vehicle_type',
        ),
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
