# Generated by Django 4.2.4 on 2025-08-09 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0005_customerenquiry_pricerange_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='truck',
        ),
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='truck',
        ),
        migrations.AlterUniqueTogether(
            name='quotationrequestitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quotationrequestitem',
            name='quotation_request',
        ),
        migrations.RemoveField(
            model_name='quotationrequestitem',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_additional_charges',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_base_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_fuel_charges',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_loading_charges',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_toll_charges',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_unloading_charges',
        ),
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.JSONField(default=list, help_text='List of vehicle items with details'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_name',
            field=models.CharField(default='Unknown Vendor', max_length=200),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='destination_pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='drop_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='origin_pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='vehicle_type',
            field=models.CharField(default='Truck', help_text='Type of vehicle needed', max_length=50),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight', max_digits=8),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton'), ('lbs', 'Pounds')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerenquiry',
            name='delivery_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='customerenquiry',
            name='delivery_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='customerenquiry',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customerenquiry',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='customerenquiry',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='pickup_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterUniqueTogether(
            name='quotationrequest',
            unique_together={('customer', 'origin_pincode', 'destination_pincode', 'pickup_date', 'drop_date')},
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
        migrations.DeleteModel(
            name='QuotationRequestItem',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='estimated_total_weight',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='suggested_price_notes',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='suggested_total_price',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='vendor',
        ),
    ]
