# Generated by Django 4.2.4 on 2025-08-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truckdocument'),
        ('quotations', '0006_alter_cartitem_unique_together_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of vehicles of this type')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Quoted price per vehicle', max_digits=10)),
                ('estimated_delivery', models.DateField(blank=True, help_text='Estimated delivery date for this item', null=True)),
                ('pickup_locations', models.JSONField(blank=True, default=list, help_text='Specific pickup locations for this item')),
                ('drop_locations', models.JSONField(blank=True, default=list, help_text='Specific drop locations for this item')),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for this vehicle item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer_suggested_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='items',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='vendor_response_to_suggestion',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='cargo_description',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='special_instructions',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='urgency_level',
        ),
        migrations.AddField(
            model_name='quotation',
            name='cargo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Vendor Response'), ('sent', 'Sent to Customer'), ('negotiating', 'Under Negotiation'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='vendor_name',
            field=models.CharField(help_text='Cached vendor name', max_length=100),
        ),
        migrations.DeleteModel(
            name='VendorEnquiryRequest',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='truck',
            field=models.ForeignKey(blank=True, help_text='Specific truck if assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='trucks.truck'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='truck_type',
            field=models.ForeignKey(blank=True, help_text='Truck type for flexible quotes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='trucks.trucktype'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(check=models.Q(('truck__isnull', False), ('truck_type__isnull', False), _connector='OR'), name='quotation_item_must_have_truck_or_type'),
        ),
    ]
